spring:
  kafka:
    producer:
      boostreap-servers:  localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cloud:
    stream:
      bindings:
        registerSession-in-0:
          destination: register_session
        deregisterSession-in-0:
          destination: deregister_session
    function:
      definition: registerSession;deregisterSession;

receive-bird:
  websocket-manager:
    node-id: 1


