server:
  port: 8081

spring:
  kafka:
    producer:
      boostreap-servers:  localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cloud:
    stream:
      bindings:
        sink1-in-0:
          destination: relay